### PR TITLE
Change `/dist` category in `.gitignore`

### PR DESCRIPTION
**Pull request by ahkhanjani**
Since the newest changes with `tsc` in this repo, `/dist` is not just about expo anymore. I couldn't decide between "production" and "typescript" categories. Would like your opinion.

### CODE REVIEW

**Comment by dBianchii** [comment]
@ahkhanjani , How are you using the dev scripts that were added by the newest improvements?
Are you doing `pnpm dev` normally so that it runs everything in parallel? Most of the time I just want to work on nextjs and I used to do `pnpm dev -F nextjs`. Now that we have multiple watchers, I haven't found the best way to run all of them quickly.

**Comment by dBianchii** [comment]
About category, Sure. placing it in typescript makes sense

**Comment by dBianchii** [comment]
I found that this script works. I placed it in my package.json:  `"dev:nextjs: "turbo dev --scope=nextjs --include-dependencies",`

**Comment by juliusmarminge** [comment]
> I found that this script works. I placed it in my package.json:  `"dev:nextjs: "turbo dev --scope=nextjs --include-dependencies",`

`turbo --filter nextjs...` should run nextjs and all it's dependencies i think

**Review by juliusmarminge — APPROVED** [review]

**Comment by ahkhanjani** [comment]
> @ahkhanjani , How are you using the dev scripts that were added by the newest improvements?
> Are you doing `pnpm dev` normally so that it runs everything in parallel? Most of the time I just want to work on nextjs and I used to do `pnpm dev -F nextjs`. Now that we have multiple watchers, I haven't found the best way to run all of them quickly.

@dBianchii I've always needed to run everything in parallel so I just run `pnpm dev`.

**Pull request merged**
