### PR TITLE
removed @bacons/text-decoder

### PR DESCRIPTION
**Pull request by necmettindev**
https://github.com/expo/expo/blob/main/packages/expo/CHANGELOG.md

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Why?

**Comment by juliusmarminge** [comment]
That's unreleased, coming in Expo 52 I think?

**Comment by necmettindev** [comment]
> That's unreleased, coming in Expo 52 I think?

nope, I guess they didn't update the changelog, also evan bacon removed the package from github.

**Comment by noxify** [comment]
This one?

https://github.com/EvanBacon/text-decoder

**Comment by juliusmarminge** [comment]
seems undefined to me, even on latest Expo:
```ts
  console.log("typeof TextEncoder", typeof TextEncoder, "typeof TextDecoder", typeof TextDecoder);
  ```

CleanShot 2024-08-08 at 12 40 05

**Pull request closed without merging**
