### PR TITLE
Fix NativeWind Typescript

### PR DESCRIPTION
**Pull request by dBianchii**
https://www.nativewind.dev/v4/getting-started/typescript

### CODE REVIEW

**Comment by dBianchii** [comment]
Before:
:angry: 
image

After:
:hugs: 
image

**Comment by juliusmarminge** [comment]
Hmm this shouldn't be necessary since i have the types included from tsconfig:

https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/tsconfig.json#L10

**Comment by dBianchii** [comment]
> Hmm this shouldn't be necessary since i have the types included from tsconfig:
> 
> https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/tsconfig.json#L10

Still getting the error even with that

**Comment by dBianchii** [comment]
I just realized we have this same exact file in src/types :thinking: Closing this because I think the error has gone away for me

**Pull request closed without merging**
