### PR TITLE
feat: change prisma for drizzle

### PR DESCRIPTION
**Pull request by juliusmarminge**

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Need https://github.com/nextauthjs/next-auth/pull/8266

**Comment by rahmat-dev** [comment]
I think you forgot to update the quick start in the readme and prisma description in other files. Can you update it, please?

image

**Comment by juliusmarminge** [comment]
> I think you forgot to update the quick start in the readme and prisma description in other files. Can you update it, please?

Done!

**Comment by rahmat-dev** [comment]
maybe you need to update package.json too 😁
image

I've updated my project but I got this error
image

image

**Pull request merged**
