### PR TITLE
chore: rsc prefetch instead of passing initialData as props

### PR DESCRIPTION
**Pull request by juliusmarminge**

### CODE REVIEW

**Comment by dBianchii** [comment]
Hi @juliusmarminge, I am getting these errors when building on vercel:

image

```
Module not found: Package path ./rsc is not exported from package /vercel/path0/apps/kdx/node_modules/@trpc/react-query
```

However, I am using the same `@trpc/react-query` version as this. Know what can be happening?

**Comment by dBianchii** [comment]
Locally it works, and even builds

**Comment by juliusmarminge** [comment]
> Locally it works, and even builds

sounds like a bad pnpm cache on Vercel? Does redeploying succeed? You need `@trpc/react-query@^11.0.0-rc.441`

**Comment by dBianchii** [comment]
> > Locally it works, and even builds
> 
> sounds like a bad pnpm cache on Vercel? Does redeploying succeed? You need `@trpc/react-query@^11.0.0-rc.441`

Oh, you're right. Can't believe vercel is so bad at detecting package.json diffs and busting cache.

Thanks!

**Pull request merged**
