### PR TITLE
feat: use nextjs app router

### PR DESCRIPTION
**Pull request by juliusmarminge**
NOT INTENDED FOR PRODUCTION USE

### CODE REVIEW

**Comment by CuriosBasant** [comment]
What is pending here? When can we expect this to be ready?

**Comment by juliusmarminge** [comment]
> What is pending here? When can we expect this to be ready?

I can get it up to date with the currently supported features in tRPC, but im not sure I'll merge it until we support appdir in create-t3-app

**Comment by CuriosBasant** [comment]
Okay thanks.
But is it ready to be used now?
I want to work with the new app dir for my new project.

**Comment by juliusmarminge** [comment]
Superseded by #424

**Pull request closed without merging**
