### PR TITLE
limiting installation to pnpm only

### PR DESCRIPTION
**Pull request by thegeeko**
making sure no will install this with yarn or npm
using [this](https://pnpm.io/only-allow-pnpm)

### CODE REVIEW

**Review by juliusmarminge — APPROVED** [review]

**Comment by juliusmarminge** [comment]
Conflicts

**Comment by juliusmarminge** [comment]
inactive

**Comment by thegeeko** [comment]
sorry about this will get to it rn

**Comment by thegeeko** [comment]
checkout #93 please

**Pull request closed without merging**
