### PR TITLE
fix: update gitignore to ignore tsbuildinfo in .cache folder

### PR DESCRIPTION
**Pull request by AMayer1997**

### CODE REVIEW

**Comment by juliusmarminge** [comment]
Is this OS dependent? It absolutely works for me right now

**Comment by AMayer1997** [comment]
I'm on macOS and the tsbuildinfo files do not get ignored

**Comment by juliusmarminge** [comment]
CleanShot 2024-10-17 at 17 25 25

they're ignored for me

**Comment by AMayer1997** [comment]
You are right. It was a VS Code issue. I'm closing the pr.

**Pull request closed without merging**
