### PR TITLE
Add eslint config to Expo project

### PR DESCRIPTION
**Pull request by CarlosBM18**
This PR adds the eslint config file for the Expo project. It also fixes the eslint error of `Error: No ESLint configuration found` appearing on the IDE.

### CODE REVIEW

**Comment by juliusmarminge** [comment]
eslint isn't a dependency in the expo package and there's no lint script, so this doesn't do anything.

Mind adding that?

**Comment by CarlosBM18** [comment]
> 

Having the ESLint extension installed on my VSCode IDE,  adding this has fixed the problem.

**Comment by juliusmarminge** [comment]
> > 
> 
> 
> 
> Having the ESLint extension installed on my VSCode IDE,  adding this has fixed the problem.

Yea but running pnpm lint won't lint expo

**Comment by CarlosBM18** [comment]
> > Having the ESLint extension installed on my VSCode IDE,  adding this has fixed the problem.
> 
> Yea but running pnpm lint won't lint expo

I got your point, now it's fixed.

**Pull request merged**
